### PR TITLE
Add support for DTO from response using an interface

### PR DESCRIPTION
**Pull request by pindab0ter**
Discussed in saloonphp/saloon#399 and saloonphp/saloon#191.

This PR support for generating DTOs from paginated responses.

### CODE REVIEW

**Comment by pindab0ter** [comment]
@Sammyjo20 could you take a look at this?

**Comment by Sammyjo20** [comment]
Hey @pindab0ter I will look at the weekend for you :) Thanks for your patience.

**Comment by pindab0ter** [comment]
Awesome, much appreciated! Sorry for pinging you directly, I just wasn't sure if this appeared on your radar at all.

**Comment by pindab0ter** [comment]
What is your opinion on the approach? Right now there's an interface and a trait, which in combination with documentation should lead users to implement it correctly.

I feel like this is in line with the rest of how Saloon handles similar features, but I'm curious about what you think.

**Comment by Andreas-Halemba** [comment]
Any updates on this one?

**Comment by pindab0ter** [comment]
We ended up doing this and dropping interest in this PR:

```php
/**
 * @return Collection<SomeDto>
 */
public function createDtoFromResponse(Response $response): Collection
{
    return collect(['parse/map collection of DTOs']);
}
```

This uses everything available with the current package, so I'll close this PR.

The only thing I don't 100% like about this is that we're not "creating a DTO from the response" but a collection of DTOs, but that's fine by me.

**Comment by Andreas-Halemba** [comment]
And where are you then supposed to call the `dto()` function to get the collection of dtos?

**Comment by pindab0ter** [comment]
Exactly. When you use `dto()` it calls the request’s `createDtoFromResponse()` or if that isn’t defined the connector’s `createDtoFromResponse()` and returns whatever you have defined to return from that, which can just as well be an `array` or a `Collection`.

For pagination `getPageItems()` returns an `array`, so we return an array from our `createDtoFromResponse()` and then simply do this:

```php
protected function getPageItems(Response $response, Request $request): array
{
    return $response->dtoOrFail();
}
```

**Pull request closed without merging**
